#Assignment-8: https://drive.google.com/file/d/1KMvOueR-cQxRJD9cADGccJxVmYDp2xkV/view

In [8]:
# Question-1:
# Addition of two Matrices:
import numpy as np
A1 = np.arange(1,10).reshape(3,3)
A2 = np.arange(10,19).reshape(3,3)

A3 = A1+A2

In [10]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
A2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
A3

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [12]:
# Question-2:
# Multiplication Tof two Matrices:
# Reusing the 3X3 Matrices Above:
A4 = A1.dot(A2)

In [13]:
A4

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [14]:
#Question-3:
#Transpose of a Matrix
A4.transpose()

array([[ 84, 201, 318],
       [ 90, 216, 342],
       [ 96, 231, 366]])

In [21]:
#Question-4:
#Program to sort words in Alphabetical Order.
alpha_string = "The quick brown fox jumps over the lazy dog"
alpha_list = list(word.lower() for word in alpha_string.split())
alpha_list.sort()
print(f"The sorted string: {alpha_list}")

The sorted string: ['brown', 'dog', 'fox', 'jumps', 'lazy', 'over', 'quick', 'the', 'the']


In [17]:
#Question-5:
#Removing Punctuations in a string:
test_string = "Greeetings{! This is a( [ ] } test string; () It has multiple punctuations,."
print(f"This is the original string: {test_string}")
punct = '''@^&*-_.%:;,<>~`!()[]{}\/'''

for st in test_string:
    if st in punct:
        test_string = test_string.replace(st, "")
        
print(f"The string after removing the punctutation: {test_string}")

This is the original string: Greeetings{! This is a( [ ] } test string; () It has multiple punctuations,.
The string after removing the punctutation: Greeetings This is a    test string  It has multiple punctuations
